#!/bin/bash

n=$((RANDOM % 10 + 10))
declare -a xs=()
declare -a ls=()
t=0; td=0

for ((i = 0; i < n; i++)); do
  xs[i]=0
  ls[i]=$((RANDOM % 1000 + 100))
  t=$((t + ls[i]))
done

for ((i = 0; i < n; i++)); do
  while [ ${xs[$i]} -lt ${ls[$i]} ]; do
    d=$((RANDOM % 100))
    xs[$i]=$((xs[i] + d))
    td=$((td + d))

    echo "$((i + 1)):$td/$t; $i:${xs[$i]}/${ls[$i]}"
  done
done
